### ISSUE TITLE
format at formatOnPaste: true 

### ISSUE THREAD

**Issue by CoffeeChaton** [RedCMD/TmLanguage-Syntax-Highlighter#16] opened 2024-06-14 16:02 UTC
1. <https://youtu.be/uouQthFaaz0> `"editor.formatOnPaste": false` vs `"editor.formatOnPaste": true`.
2. <https://youtu.be/pXra4k309XY> mouse jumps far.

```jsonc
// settings.json

{
    // bad case
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "typescript.format.semicolons": "insert",
    "[json-tmLanguage]": {
        "editor.defaultFormatter": "RedCMD.tmlanguage-syntax-highlighter"
    },
}
```

if `"editor.formatOnPaste": true` , format will get weird for a moment,
for me, the biggest problem is that the mouse will wander far away, like `exp2`.

I think may the latest status was not updated (via `onDidChangeTextDocument()`) before `Format`.

**Comment by RedCMD** [comment] 2024-06-14 21:32
can confirm

strangely it only occurs when indentation is set to 'spaces'
'tabs' is perfectly fine

this _may_ be a VSCode bug

**Comment by RedCMD** [comment] 2024-06-14 22:21
Fixed in latest Pre-Release
was caused by me not counting for the (spaces) tab width for the initial indentation

**Closed by RedCMD** 2024-06-14 22:21 UTC
Labels: bug
