### ISSUE TITLE
Scope theme colors don't update

### ISSUE THREAD

**Issue by vanowm** [RedCMD/TmLanguage-Syntax-Highlighter#2] opened 2022-10-04 03:12 UTC
It seems changes in `package.json` are not reflected in `tmLanguage.json`
And some scopes don't have any colors:
![image](https://user-images.githubusercontent.com/511517/193725390-06a704dd-1711-4414-b79d-722e3f6554b8.png)

![image](https://user-images.githubusercontent.com/511517/193726258-d6eedb82-cf09-44cd-9e1c-1ef55b10bab6.png)

I think it was one time after VSCode restart that is showed all the missing colors for a split of a second, then removed them.

[EDIT]
might be conflicting with other extension? will check

**Comment by RedCMD** [comment] 2022-10-04 03:25
Any changes in `package.json` requires 2 restarts of vscode to take affect

Do the colours work on your language?
(not the json file)

Currently I'm just piggy backing off vscodes scope highlighting
it only takes the current themes colours/scopes into account
idk if the settings in `package.json` modify's it

**Comment by vanowm** [comment] 2022-10-04 03:46
Yes, the colors are working properly in that extension.
Two restarts of vscode??? That's doesn't sound like "real time" 😉

Tried it on fresh portable VSCode with default settings only this extension installed - it doesn't pick up any colors after multiple restarts:
![image](https://user-images.githubusercontent.com/511517/193729132-77343c08-9b41-427a-9de6-48ba922f0056.png)

**Comment by RedCMD** [comment] 2022-10-04 03:52
the two restarts is default vscode behavior

you adding the scopes to your extension or theme?
I only support themes scopes

**Comment by vanowm** [comment] 2022-10-04 04:02
It's syntax highlighting rules for the extension.
![image](https://user-images.githubusercontent.com/511517/193731478-eabbb697-2b83-4771-9dc2-47fdf756e528.png)

It is strange though that it's picking up some colors and not in fresh vscode

**Comment by RedCMD** [comment] 2022-10-04 04:46
Its working for me
![image](https://user-images.githubusercontent.com/33529441/193736316-70b99633-0d2f-4943-b33f-261a6fb0786b.png)
![image](https://user-images.githubusercontent.com/33529441/193736336-8c58caa7-efa2-4ad8-856b-0343165fa018.png)

**Comment by vanowm** [comment] 2022-10-04 10:40
How about on [this](https://github.com/vanowm/AutoIt-VSCode/tree/a6ddc236281f0d388c1003172eda446c64c9d545)?

**Comment by RedCMD** [comment] 2022-10-04 17:44
![image](https://user-images.githubusercontent.com/33529441/193889455-a007f46c-950f-4344-a54e-dd06449d887f.png)

**Comment by RedCMD** [comment] 2022-10-04 18:16
I just had a quick look
it is indeed not working
I'll have to figure out later

**Comment by RedCMD** [comment] 2022-10-05 03:46
seems only one extension can define `editor.tokenColorCustomizations` at a time
![image](https://user-images.githubusercontent.com/33529441/193975297-3b2eb84d-ea99-4622-b6d4-999d4f622b96.png)
I removed `editor.tokenColorCustomizations` from my test extension and yours started working again

This doesn't affect just my extension
it affects vscodes textmate in general

if you are launching your extension using vscodes debugging mode
then only one extension is modifying `editor.tokenColorCustomizations`
so it will appear to work correctly

**Comment by vanowm** [comment] 2022-10-05 11:11
On fresh install I only tested your extension, nothing else.
P.S.
On your screenshots, you are testing it against wrong commit/branch of autoit extension. For me as you can see on first screenshot, these names worked fine too, including names that ended with a color name (blue, red, brown), however on fresh install none are highlighted.

**Comment by RedCMD** [comment] 2022-10-05 18:56
> On fresh install I only tested your extension, nothing else.

vscode uses the current theme to colour in scopes
your extension needs to be enabled for it to add your scopes to the current theme
otherwise vscode will default back to standard white

I have both yours and my extension enabled in the same instance of vscode
![image](https://user-images.githubusercontent.com/33529441/194139500-7982dc0f-02cd-4de2-b1ef-47b520b67e1b.png)

**Comment by vanowm** [comment] 2022-10-05 19:07
I think there is misunderstanding 😉. My extension has nothing to do with this. When I open workspace where the code of my extension is in fresh vscode with only RedCMD installed, it doesn't show the colors.

**Comment by RedCMD** [comment] 2022-10-05 20:28
which is currently intended behavior
if your current theme doesn't support those scopes
then they won't have any colour

maybe I can add a language feature to load scopes from inactivate extensions
problem is I have to manually check every file for it then
I can't use any builtin vscode features
and then what should happen when there is multiple workspaces and extensions?
how to handle injections and embedding? 
manually emulating an environment is much harder than just using the current one
is much simpler, as vscode handles everything

**Comment by RedCMD** [comment] 2024-01-03 10:33
I didn't end up using semantic highlighting. VSCode TextMate scopename assigning is way too stupidly complex

Instead I try to locate the `package.json` file, copy the `editor.tokenColorCustomizations` setting and apply it to the VSCode global settings file.
Sadly this will overwrite any `editor.tokenColorCustomizations` thats already there
so I make a copy of that and save it as `editor.tokenColorCustomizations_bak`
and attempt to reload it back when closing files (TODO: needs more work)

**Comment by vanowm** [comment] 2024-01-03 21:05
In my tests, since we can't control when, which extension initializing first, all we can do is merge existing setting with ours, not just replace it. But again we can't really trust that the global setting is up-to-date when extension starts, even merging might not be 100% reliable solition...

**Comment by RedCMD** [comment] 2024-01-03 22:39
Technically VSCode doesn't ever merge the settings either
so I'll just follow the same way and just temporary replace the settings when clicking on a `package.json` file or `json-textmate` languageId file

I don't have to worry about the extension initializing order as this feature is only for in the context that the extension providing the `editor.tokenColorCustomizations` setting isn't loaded in the same instance of VSCode

**Comment by RedCMD** [comment] 2024-01-10 09:15
I've published a pre-release version with the changes
see if its like how you want
and that theres no bugs :}

**Comment by RedCMD** [comment] 2024-03-02 22:24
Now available in the full release 2.3.0

**Closed by RedCMD** 2024-03-02 22:24 UTC
Labels: enhancement
